name: Textile Stories
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74398
title: Textile Hive Stories
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e8e6da'
    - '#d0d0c6'
    - '#9c9990'
    - '#71706c'
    - '#e69582'
  brandStrength: 0.25
  lightness: 0.923055661143735
  saturation: 0.9563691979274154
  rhythmicContrast: 0.8211394699756056
purpose: []
